#!/bin/sh

# GET THE TYPE OF THE SYSTEM (Darwin, Linux)
system_type=$(uname -s)


# INIT GIT SUBMODULES
# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
# cd "$HOME"
# echo "\nYADM SUBMODULE INIT"
# yadm submodule update --recursive --init

    
# Check if the system type is Linux
if [ "$system_type" = "Linux" ]; then
    # Check if it's Ubuntu
    if [ -f /etc/os-release ] && grep -q "^ID=ubuntu" /etc/os-release; then

        # Install lolcat package with apt
	if ! which lolcat >/dev/null 2>&1; then
	    echo "\nINSTALLING LOLCAT USING APT"
	    sudo apt update
	    sudo apt install lolcat
	fi
    fi
fi

# TODO:INSTALL GIT




# INSTALL ZSH PLUGINS
plugins_dir=~/.config/zsh/plugins  # Base dir to install zsh plugins
mkdir -p $plugins_dir # Create plugins_dir if it does not exists

if [ ! -d $plugins_dir/zsh-autosuggestions ]; then
    echo "\nINSTALLING ZSH AUTOSUGGESTIONS"
    git clone https://github.com/zsh-users/zsh-autosuggestions $plugins_dir/zsh-autosuggestions
fi


if [ ! -d $plugins_dir/zsh-syntax-highlighting ]; then
    echo "\nINSTALLING ZSH SYNTAX HIGHLIGHTING"
    git clone https://github.com/zsh-users/zsh-syntax-highlighting $plugins_dir/zsh-syntax-highlighting
fi




# SETUP P10K THEME
themes_dir=~/.config/zsh/themes  # Base dir to install zsh themes
mkdir -p $themes_dir # Create themes_dir if it does not exists

if [ ! -d $themes_dir/powerlevel10k ]; then
    echo "\nINSTALLING POWERLEVEL10K THEME"
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $themes_dir/powerlevel10k
fi

