#!/bin/sh

# GET THE TYPE OF THE SYSTEM (Darwin, Linux)
system_type=$(uname -s)


# INIT GIT SUBMODULES
# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"
echo "Init submodules"
yadm submodule update --recursive --init


# Check if the system type is Darwin (macOS)
if [ "$system_type" = "Darwin" ]; then
    # Check if Homebrew is installed
    if ! command -v brew &> /dev/null; then
        echo "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    
    # Install lolcat package with Homebrew
    echo "Installing lolcat with Homebrew..."
    brew install lolcat

# Check if the system type is Linux
elif [ "$system_type" = "Linux" ]; then
    # Check if it's Ubuntu
    if [ -f /etc/os-release ] && grep -q "^ID=ubuntu" /etc/os-release; then
        # Install lolcat package with apt
        echo "Installing lolcat with apt..."
        sudo apt update
        sudo apt install lolcat
    fi
fi
